# Generated by Django 4.2 on 2026-02-28 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('registered_color', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('STOLEN', 'Stolen')], default='NORMAL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('detected_color', models.CharField(max_length=30)),
                ('detected_vehicle_type', models.CharField(max_length=30)),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('toll_id', models.CharField(max_length=50)),
                ('toll_name', models.CharField(max_length=100)),
                ('lane_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detected_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
