# Generated by Django 4.2 on 2026-02-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedvehicle',
            name='image',
        ),
    ]
