# Generated by Django 4.2 on 2026-02-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('alert_reason', models.CharField(max_length=100)),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('toll_id', models.CharField(max_length=50)),
                ('toll_name', models.CharField(max_length=100)),
                ('lane_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alert_images/')),
                ('detected_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.detectedvehicle')),
            ],
        ),
    ]
