# Generated by Django 4.2 on 2026-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('registered_color', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('STOLEN', 'Stolen')], default='NORMAL', max_length=20)),
            ],
        ),
    ]
