# Generated by Django 4.2 on 2026-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaster',
            name='contact_info',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
