# Generated by Django 4.2 on 2026-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('detected_color', models.CharField(max_length=30)),
                ('database_color', models.CharField(blank=True, max_length=30, null=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('detected_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alert_images/')),
            ],
        ),
    ]
