# Generated by Django 4.2 on 2026-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_uploadedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevidence',
            name='database_vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alertevidence',
            name='detected_vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
