# Generated by Django 4.2 on 2026-02-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertevidence_database_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevidence',
            name='contact_info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alertevidence',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
